### ISSUE TITLE
Link to EW2024 source code points to private repository?

### ISSUE THREAD

**Issue by RudolphRiedel** [Bridgetek/Bridgetek.github.io#2]
See:
https://bridgetek.github.io/tutorials/ew2024_photobooth/html/Project%20Structure.html

There is a link:
https://bridgetek.github.io/tutorials/ew2024_photobooth/html/github.com/BridgetekChip/EveDemoApps/releases/tag/EW2024_v1.3.2

But https://github.com/BridgetekChip/EveDemoApps/ does not exist, likely because it is set to private.

**Comment by RudolphRrr** [comment]
Nice, thank you, the ticket was only about the not working link, but this should be even better. :-)
